# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название акции')),
                ('text', models.TextField(blank=True, max_length=16384, null=True, verbose_name='Дополнительный текст')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('citizenship', models.BooleanField(default=False, verbose_name='Не гражданин РФ.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=26, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num_home', models.CharField(max_length=5, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Пустой', 'Пустой'), ('Зерегистрированный А', 'Зерегистрированный А'), ('Зерегистрированный Б', 'Зерегистрированный Б')], default='Новый', max_length=24, verbose_name='Статус регистрации')),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Консультант',
                'verbose_name_plural': 'Консультанты',
                'ordering': ['-registered_date'],
            },
        ),
    ]
