# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='shares/images'),
        ),
        migrations.AddField(
            model_name='share',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='shares/images'),
        ),
        migrations.AddField(
            model_name='share',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='shares/images'),
        ),
        migrations.AddField(
            model_name='share',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='shares/images'),
        ),
        migrations.AddField(
            model_name='share',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='shares/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
