# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171119_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='addressHref',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Ссылка перенаправляющая на карты(Google/Yandex)'),
        ),
    ]
