# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:58
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171119_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='button_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона кнопок сайта'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопок сладера'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='checkbox_field_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона блока чекбокса регистрации'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='checkbox_field_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет текста чекбокса регистрации'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='close_menu_button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопоки закрытия меню'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='default_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Фон сайта'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='default_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта по умолчанию'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='default_link_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='default_link_hover_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Стандартный цвет ссылок при наведении'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='footer_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона нижней части страницы'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='footer_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта нижней части страницы'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='header_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона верхней части страницы'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='header_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта верхней части страницы'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='headings_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта заголовков'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='menu_link_hover_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона ссылок при наведении'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='menu_link_hover_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет ссылок меню при наведении'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='open_menu_button_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона кнопоки открытия меню'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='open_menu_button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопоки открытия меню'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='slider_buttons_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона кнопок сладера'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='slider_buttons_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопок сладера'),
        ),
    ]
