# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 09:53
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='button_hover_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона кнопок при наведении'),
        ),
        migrations.AddField(
            model_name='custom',
            name='button_hover_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопок при наведении'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопок'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='slider_buttons_bg',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет фона кнопок слайдера'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='slider_buttons_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта кнопок слайдера'),
        ),
    ]
