# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='iframe',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='addressHref',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка перенаправляющая на карты(Google/Yandex)'),
        ),
    ]
