# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171119_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='iframe',
            field=models.TextField(default=None, max_length=1000, verbose_name='Видео'),
        ),
    ]
