# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171119_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='iframe',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.TextField(default=None, max_length=500, verbose_name='Ссылка на видео'),
        ),
    ]
