# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:24
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171119_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='custom',
            name='menu_link_active_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта активной ссылки'),
        ),
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.TextField(default=None, max_length=50, verbose_name='Идентификатор видео'),
        ),
    ]
