# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20171119_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoId',
            field=models.CharField(max_length=50, verbose_name='Идентификатор видео'),
        ),
    ]
