# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 14:26
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171119_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='slide_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='custom',
            name='slide_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='custom',
            name='slide_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='custom',
            name='slide_4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='custom',
            name='slide_5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='menu_link_active_color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True, verbose_name='Цвет шрифта активной ссылки'),
        ),
    ]
